### ISSUE TITLE
NoSuchFieldError with Spigot 1.13.2

### ISSUE THREAD

**Issue by SlimeDog** [CraftG/WatchCat#101]
Spigot 1.13.2
WatchCat 2.1.3-b5

Yes, I know, early to the party. :)
ISSUE TYPE: BUG/ERROR

SERVER LOG: 
```
[13:38:50] [Netty Epoll Server IO #0/ERROR]: [WatchCat] Unhandled exception occured in onPacketReceiving(PacketEvent) for WatchCat
java.lang.NoSuchFieldError: a
	at xyz.WatchCat.‎‎‎ ‎‎ ‎ .‎‎ ‎ ‎(AlignedAxisBBGetter_v1_13_R2.java) ~[WatchCat-2.1.3-b5.jar:?]
	at xyz.WatchCat.‎ ‎ ‎ ‎ ‎ ‎.‎‎ ‎ ‎ ‎‎ (Utilities.java) ~[WatchCat-2.1.3-b5.jar:?]
	at xyz.WatchCat.‎‎ ‎ ‎‎‎ .‎ (PositionListener.java) ~[WatchCat-2.1.3-b5.jar:?]
	at xyz.WatchCat.‎‎ ‎ ‎‎‎ .onPacketReceiving(PositionListener.java) ~[WatchCat-2.1.3-b5.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:509) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib-4.4.0-b422.jar:4.4.0-b422]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b423
0a9]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.13.2.jar-2018-10-22-1334:git-Spigot-a1ba5fe-b4230a9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by CraftG** [comment]
1.13.2 will be supported in the next version :)

**Comment by SlimeDog** [comment]
Assumed as much. Just wanted to point at one of the issues.
