### ISSUE TITLE
未知报错

### ISSUE THREAD

**Issue by g530775** [CraftG/WatchCat#71]
`[01:07:24] [Craft Scheduler Thread - 3/INFO]: (WatchCat) ----------------------------------------
[01:07:24] [Craft Scheduler Thread - 3/INFO]: (WatchCat) | Loading WatchCat 1.7.0.6. Players cannot join the server until complete
[01:07:25] [Craft Scheduler Thread - 3/INFO]: (WatchCat) | Loaded configuration files
[01:07:25] [Craft Scheduler Thread - 3/INFO]: (WatchCat) | Registered commands
[01:07:25] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[01:07:25] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin WatchCat v1.7.0.6 generated an exception while executing task 112
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93)
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:373)
	at com.comphenix.protocol.injector.PacketFilterManager.initializePlayers(PacketFilterManager.java:946)
	at com.comphenix.protocol.injector.PacketFilterManager.incrementPhases(PacketFilterManager.java:462)
	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:405)
	at xyz.WatchCat.IiIiIiIIIi.<init>(fj)
	at xyz.WatchCat.Bukkit_WatchCat.short(i)
	at xyz.WatchCat.IIIIIiIiII.run(i)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.IllegalArgumentException: 'PROTOCOL-0' is already in use
	at io.netty.util.UniqueName.<init>(UniqueName.java:53)
	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47)
	at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39)
	at com.comphenix.protocol.injector.netty.ChannelInjector.<clinit>(ChannelInjector.java:88)
	... 13 more`
我不知道什么原因有可能是ProtocolLib原因...

**Comment by CraftG** [comment]
换最新版ProtocolLib试试

**Comment by g530775** [comment]
还有...我那个Amera的step还能够使用...
